In [1]:
import numpy as np
import cv2
import scipy.signal as sig

input = np.array(((1,4,7,6,8,4), (4,3,2,9,0,1), (9,4,5,0,4,7), (4,2,3,9,5,8), (1,0,9,3,5,7), (9,3,4,5,7,4)))
filter = np.array(((0.5, 0.78, 1.32),(1.1,2.11, 1.43),(0.39, 0.13, 0.89)))
pad_width = filter.shape[0] // 2
padded_input = np.pad(input, pad_width, "edge")

output = sig.correlate2d(padded_input, filter, "same")[1:-1, 1:-1]
print(output)
# output = np.convolve(test_matrix, filter)

[[20.24 36.14 52.57 52.49 48.12 36.38]
 [31.93 34.93 37.98 45.44 32.6  24.64]
 [47.55 36.96 39.07 26.03 35.55 41.39]
 [33.02 35.53 31.14 45.57 52.3  59.61]
 [18.32 28.95 44.64 46.94 49.24 56.39]
 [41.81 41.79 36.01 46.84 47.05 45.87]]
